"""empty message

Revision ID: e86bff7b59bd
Revises: 5fa30e530db4
Create Date: 2020-08-22 00:39:42.723871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86bff7b59bd'
down_revision = '5fa30e530db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('cost', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('food', sa.Column('location', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'location')
    op.drop_column('food', 'cost')
    # ### end Alembic commands ###
